version: '3'
services:

  nginx:
    build: requirements/nginx/
    # image: nginx_image
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/Desktop/inception:/var/www/html"
    depends_on:
      - wordpress
      - mariadb
    networks:
      - frontend

  mariadb:
    build: requirements/mariadb/
    # image: mariadb_image
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}

  wordpress:
    build: requirements/wordpress/
    # image: wordpress_image
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "~/Desktop/inception:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/gvenet/data/db_data
  
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/gvenet/data/wp_data
