version: '3'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - "/home/gvenet/wp_data:/var/www/html"
    depends_on:
      - wordpress
      - mariadb
    networks:
      - default

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: on-failure
    volumes:
      - "/home/gvenet/wp_data:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - default
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - "/home/gvenet/db_data:/var/lib/mysql"
    networks:
      - default
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
    
networks:
  default:
    external:
      name: inception_network