version: '3'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - frontend
    # networks:
    #   - default

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: on-failure
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    # networks:
    #   - default
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    # networks:
    #   - default
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/gvenet/data/db_data
  
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/gvenet/data/wp_data




# networks:
#   default:
#     external:
#       name: inception_network