ALTER USER 'root' @'URL' IDENTIFIED BY 'MYSQL_ROOT_PWD';
CREATE DATABASE WP_DATABASE_NAME;
CREATE USER 'WP_DATABASE_USR' @'%' IDENTIFIED BY 'WP_DATABASE_PWD';
GRANT ALL PRIVILEGES ON *.* TO 'root' @'URL' WITH
GRANT OPTION;
GRANT ALL PRIVILEGES ON WP_DATABASE_NAME.* TO 'WP_DATABASE_USR' @'%';
FLUSH PRIVILEGES;
QUIT